package kotlinx.parcelize;

import android.os.Parcel;
import kotlin.NotImplementedError;
import org.jetbrains.annotations.C12579k;

/* renamed from: kotlinx.parcelize.c */
public interface C12185c<T> {

    /* renamed from: kotlinx.parcelize.c$a */
    public static final class C12186a {
        @C12579k
        /* renamed from: a */
        public static <T> T[] m48775a(@C12579k C12185c<T> cVar, int i) {
            throw new NotImplementedError("Generated by Android Extensions automatically");
        }
    }

    /* renamed from: a */
    void mo24797a(T t, @C12579k Parcel parcel, int i);

    /* renamed from: b */
    T mo24798b(@C12579k Parcel parcel);

    @C12579k
    T[] newArray(int i);
}
