package kotlinx.android.parcel;

import android.os.Parcel;
import kotlin.NotImplementedError;
import org.jetbrains.annotations.C12579k;

/* renamed from: kotlinx.android.parcel.b */
public interface C11685b<T> {

    /* renamed from: kotlinx.android.parcel.b$a */
    public static final class C11686a {
        @C12579k
        /* renamed from: a */
        public static <T> T[] m45892a(@C12579k C11685b<T> bVar, int i) {
            throw new NotImplementedError("Generated by Android Extensions automatically");
        }
    }

    /* renamed from: a */
    void mo23556a(T t, @C12579k Parcel parcel, int i);

    /* renamed from: b */
    T mo23557b(@C12579k Parcel parcel);

    @C12579k
    T[] newArray(int i);
}
