package com.google.android.gms.common.api.internal;

import androidx.annotation.C0359n0;
import com.google.android.gms.common.api.C40663m;
import com.google.android.gms.common.api.C40669r;
import com.google.android.gms.common.api.C40670s;
import com.google.android.gms.common.api.C40672u;
import com.google.android.gms.common.api.C40673v;
import com.google.android.gms.common.api.Status;
import com.google.android.gms.common.internal.C40843u;
import com.google.android.gms.common.internal.C40858y;
import java.util.concurrent.TimeUnit;

/* renamed from: com.google.android.gms.common.api.internal.v2 */
public final class C40638v2<R extends C40669r> extends C40663m<R> {

    /* renamed from: a */
    public final Status f103602a;

    public C40638v2(Status status) {
        C40843u.m166203m(status, "Status must not be null");
        C40843u.m166192b(!status.mo133655p0(), "Status must not be success");
        this.f103602a = status;
    }

    /* renamed from: c */
    public final void mo133783c(@C0359n0 C40663m.C40664a aVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @C0359n0
    /* renamed from: d */
    public final R mo133784d() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @C0359n0
    /* renamed from: e */
    public final R mo133785e(long j, @C0359n0 TimeUnit timeUnit) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* renamed from: f */
    public final void mo133687f() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* renamed from: g */
    public final boolean mo133786g() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* renamed from: h */
    public final void mo133787h(@C0359n0 C40670s<? super R> sVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* renamed from: i */
    public final void mo133788i(@C0359n0 C40670s<? super R> sVar, long j, @C0359n0 TimeUnit timeUnit) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @C40858y
    @C0359n0
    /* renamed from: j */
    public final <S extends C40669r> C40673v<S> mo133789j(@C0359n0 C40672u<? super R, ? extends S> uVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @C0359n0
    /* renamed from: k */
    public final Status mo134074k() {
        return this.f103602a;
    }
}
